name: Docker Image from master

on:
  push:
    branches:
      - master

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build the Docker images
          run: |
            docker login -u metalpod -p ${{ secrets.DOCKER_HUB_TOKEN }}
            make dockerimages
            make dockerpush